language: php

env:
    -REDIS_HOST=127.0.0.1

php:
    - 7.1.3
    - 7.2

services:
    - redis-server

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source

script:
    - mkdir -p ./build/logs
    - ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/php-coveralls -v

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/30886f28c25b1e31088f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
